### ISSUE TITLE
make check fails on Fedora 21 due to using gdk-pixbuf 2.31.1

### ISSUE THREAD

**Issue by mtasaka** [clear-code/cutter#19]
Now on Fedora 21 (already released) make check (on both cutter 1.2.4 and git head) fails like:
```
===============================================================================
Failure: test_inspect
<expected == gcut_object_inspect(G_OBJECT(pixbuf1))>
expected: <"#<GdkPixbuf:0x97c1958 colorspace=<#<GdkColorspace: rgb(GDK_COLORSPACE_RGB:0)>>, n-channels=<4>, has-alpha=<TRUE>, bits-per-sample=<8>, width=<100>, height=<100>, rowstride=<400>, pixels=<((gpointer) 0x98b56c8)>>">
  actual: <"#<GdkPixbuf:0x97c1958 colorspace=<#<GdkColorspace: rgb(GDK_COLORSPACE_RGB:0)>>, n-channels=<4>, has-alpha=<TRUE>, bits-per-sample=<8>, width=<100>, height=<100>, rowstride=<400>, pixels=<((gpointer) 0x98b56c8)>, pixel-bytes=<NULL>>">

diff:
? "#<GdkPixbuf:0x97c1958 colorspace=<#<GdkColorspace: rgb(GDK_COLORSPACE_RGB:0)>>, n-channels=<4>, has-alpha=<TRUE>, bits-per-sample=<8>, width=<100>, height=<100>, rowstride=<400>, pixels=<((gpointer) 0x98b56c8)>, pixel-bytes=<NULL>>"

./gdkcutter-pixbuf/test-gdkcut-pixbuf.c:143: test_inspect(): cut_assert_equal_string_with_free(expected, gcut_object_inspect(((((GObject*) g_type_check_instance_cast ((GTypeInstance*) ((pixbuf1)), (((GType) ((20) << (2))))))))), )
===============================================================================
```
(and now cutter srpm on Fedora FTBFS (fail to build from source) on Fedora 21, 22)

I guess this is due to this commit (and bug report):
https://git.gnome.org/browse/gdk-pixbuf/commit/?id=862e3890f54aaeb8589a6ee4c146f1fb50556004
https://bugzilla.gnome.org/show_bug.cgi?id=732297

Current "unstable" GdkPixbuf API:
https://developer.gnome.org/gdk-pixbuf/unstable/gdk-pixbuf-The-GdkPixbuf-Structure.html#GdkPixbuf--pixel-bytes

I think it is safe that 2.31.1 and above has "pixel-bytes”.

P.S. first of all Fedora 21 should not use such an "unstable" stage of gdk-pixbuf2, I think :( however that happened...

**Comment by mtasaka** [comment]
> I think it is safe that 2.31.1 and above has "pixel-bytes”.
meant I think it is safe to think that 2.31.1 and above has "pixel-bytes”.

**Comment by kou** [comment]
Thanks for your report.
I've fixed it.

I confirmed that gdk-pixbuf 2.31.0 has "pixel-bytes".

**Comment by mtasaka** [comment]
Confirmed, thank you.
