### ISSUE TITLE
Test suite "segfaults" on Fedora 22

### ISSUE THREAD

**Issue by mtasaka** [clear-code/cutter#20]
With Fedora 22 (GLib is now 2.43.90, same as 2.43.4) using git head (3947d29299645) make check fails like
```
FAIL: run-test.sh
============================================================================
Testsuite summary for cutter 1.2.4
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See test/test-suite.log
Please report to kou@clear-code.com
============================================================================
```

and test/test-suite.log is:
https://bugzilla.redhat.com/attachment.cgi?id=993869

(While I have not investigated in detail) it looks like (again just my guess) this segv is derived from cutter/test-cut-test.c:323. and the signal wasn't caught properly...???

**Comment by kou** [comment]
Thanks for your report.
It's difficult to debug without reproducible environment...

It seems that `GSource` of `SoupMessage` isn't stopped even libsoup related tests (`test/soupcutter/test-*.c`) are finished.

It may be fixed by using new libsoup API... It seems that `SoupServer` changes `GMainContext` handling.

**Comment by kenhys** [comment]
I've uploaded package for testing on F-22. "make check" was succeeded on F-22.

Here is the update for testing on F-22.
https://admin.fedoraproject.org/updates/FEDORA-2015-2555/cutter-1.2.4-4.fc22

@mtasaka, could you try testing package whether the reported issue is still exists?

**Comment by mtasaka** [comment]
Umm... now both on F-22 i686/x86_64 this segv is no longer reproducible, with both Fedora 1.2.4-4 and git head...

Once closing, will report again when this issue reappears, thank you.
