### ISSUE TITLE
Release 1.2.5

### ISSUE THREAD

**Issue by kenhys** [clear-code/cutter#21]
修正がいくつかたまっているのとしばらく新しいのをだしていないので、今月Cutter 1.2.5としてリリースする。

懸案はホスティングでsf.netを利用しているが、依然としてshellサービスが復旧していないということ。
リポジトリやtar.gzをアップロードするのに支障がある。7/22付のblogでまだ駄目だと告知されている。
see http://sourceforge.net/blog/sourceforge-project-web-service-online/

githubにもtar.gzは置いているので、復旧が長引きそうならパッケージはあとでということにするかも。

**Comment by kenhys** [comment]
http://sourceforge.net/blog/sourceforge-infrastructure-and-service-restoration-update-for-724/
をみると、Project web serviceは復旧した模様なので、cutter.sourceforge.netはおそらく更新できる。
frs.sourceforge.netはまだ復旧中のようだ。

**Comment by cosmo0920** [comment]
質問です！
1.2.5のタグが打たれているリリースページにautogen.shが実行済みのソースコード一式がアップロードされる予定でしょうか？
Sourceforge.netに置かれているcutter 1.2.4のソースコードにはconfigureスクリプトが有る状態のものが置かれていました。
Homebrewのcutter.rb https://github.com/Homebrew/homebrew/blob/master/Library/Formula/cutter.rb#L20 はautomakeにもautoconfにも依存してないのでconfigureスクリプトが含まれている状態の物が有るとありがたいなぁと思った次第です。

**Comment by cosmo0920** [comment]
口頭で sourceforge.netにあるcutter 1.2.5を使うと言うことで了解しました。

**Comment by kenhys** [comment]
sf.netのfile upload serviceが復旧したので、パッケージをビルドしてアップロードしておいた。
