### ISSUE TITLE
Unable to work the tutorial on a Mac (MacOS Mojave 10.14.4)

### ISSUE THREAD

**Issue by wbreeze** [clear-code/cutter#40]
Thank you for cutter. I've looked at the source and there's a lot to it. It is not a casual effort. Pardon me for not making a PR. It would be mostly changes to the tutorial instructions that might or might not be universally applicable. Or perhaps a version specific to Mac. In the end; however, I've run-into a library search problem that I'm not sure how to solve.

First, the problem:
```
~/Documents/p.temp/stack$ test/run-test.sh
-bash: test/run-test.sh: No such file or directory
~/Documents/p.temp/stack$ test/run_test.sh
Making all in src
/Library/Developer/CommandLineTools/usr/bin/make  all-am
Making all in test
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all-am'.

** (cutter:89812): WARNING **: 09:44:21.468: can't load a shared object for test case: test/.libs/test_stack.so: dlopen(test/.libs/test_stack.so, 1): Library not loaded: /usr/local/lib/libstack.0.dylib
  Referenced from: /Users/dcl/Documents/p.temp/stack/test/.libs/test_stack.so
  Reason: image not found


Finished in 0.000153 seconds (total: 0.000000 seconds)

0 test(s), 0 assertion(s), 0 failure(s), 0 error(s), 0 pending(s), 0 omission(s), 0 notification(s)
0% passed
~/Documents/p.temp/stack$
```
While `libstack.0.dylib` exists in `src/.libs`, it is being searched as `/usr/local/lib/libstack.0.dylib` I'm not sure how to fix it.

I like cutter because it works most like miniTest, with which I'm familar. It:
- has similar output
- has setup and teardown functions
- finds the tests, so there's no need to write a lot of test harness code. Just write tests.

If only I could make it work!

Following are some notes from following the tutorial. There were a number of differences.
For starters, I installed with `brew install cutter autoconf automake libtool` This gave the following versions:
```
cutter 1.2.6
autoconf (GNU Autoconf) 2.69
glibtool (GNU libtool) 2.4.6
automake (GNU automake) 1.16.1
```

- The brew `libtool` installs as `glibtool` in order not to overwrite `libtool` already installed. However `libtoolize` is not linked into the path. Thus, in `autogen.sh` I replaced `libtoolize` with `glibtoolize`.
- Note, GNU build tools looks like it is moving away from `alocal` and the invocations of `autogen.sh` toward use of `autoreconf`. See for example, [Future of alocal](https://www.gnu.org/software/automake/manual/automake.html#Future-of-aclocal)
- Upgraded the use of `AM_INIT_AUTOMAKE` to call it without parameters. See [Automake public macros](https://www.gnu.org/software/automake/manual/automake.html#Public-Macros)
- I'm using underscores '_' in place of hyphens '-' in the file names. Personal preference and hoping that won't make problems.
- `glibtoolize` had suggestions for using m4, which I followed. They were:
```
glibtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am
glibtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
glibtoolize: and rerunning glibtoolize and aclocal.
```
(Backing-out these changes didn't solve my linking problem.)
- Having set-up `stack.h`, I got linker errors for undefined symbols. Cutter ran without errors, only not running any tests.
- After setting-up `test/run-test.sh`, `make -s check` needed me to rerun `autogen.sh` in order to install `test-driver`.
- I was unable to add the `echo-cutter` target to `test/Makefile.am` due to this error:
```
config.status: error: in `/Users/dcl/Documents/p.temp/stack':
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  Try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
```
- Rurunning `autogen.sh` I got a warning asking to substitute `AM_CPPFLAGS` for `INCLUDES`. I changed "INCLUDES" to "test_stack_la_CPPFLAGS"
- After implementing `stack.c` and setting it up for for compile, zero tests run and I get the dynamic link library not found error.

Find the files in this gist: https://gist.github.com/wbreeze/4b49948740278cdd156c5f9478bfebf5

**Comment by kou** [comment]
Thanks for your feedback.
I'll look into this after RubyKaigi 2019. I need to give a talk at there.

It seems that your `test/run-test.sh` doesn't have `DYLD_LIBRARY_PATH` setting that is described in the tutorial.

**Comment by wbreeze** [comment]
Thank you very much for spotting the problem. The text said that those lines were for Cygwin. Now I see that "Darwin" is the `uname` for my OS, and that DYLD_LIBRARY_PATH set there applies.

The one line change to the tutorial made by the PR might help others avoid making my mistake.
