### ISSUE TITLE
Certificate for https://cutter.osdn.jp/ has expired

### ISSUE THREAD

**Issue by abetomo** [clear-code/cutter#46]
An error was displayed when I accessed the site.
It appears to have expired on 2023/05/22.

**Comment by kou** [comment]
Oh...
We should migrate to something to other maintained services such as GitHub Pages...

FYI: We can use https://cutter.osdn.io/ as workaround... But it will be invalid soon...

**Comment by abetomo** [comment]
Thanks for the info.
I no longer get the certificate error.
